//! Loading the corpus.
//!
//! One case per file. A program, the input it reads, the output it must produce and whatever
//! else it asks for are one thing, and were three files that only a shared stem tied together:
//! a program whose `.out` was missing was a panic at load, and a `.in.json` whose stem was
//! misspelt was silently a program that reads no input.
//!
//! Read by both the agreement harness and the native backend's tracker, which were two copies
//! of the same directory walk.

#![allow(dead_code)]

use std::path::{Path, PathBuf};

use serde::Deserialize;

/// The file as written. `deny_unknown_fields` is the point of the struct: a misspelt key would
/// otherwise be a case that quietly asks for nothing extra, which looks exactly like a case that
/// passes.
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Fields {
    program: String,
    #[serde(default)]
    input: Option<String>,
    #[serde(default)]
    output: Option<String>,
    /// Set when the program compiles but every backend has to refuse to run it. What each says
    /// while refusing is its own business, so only the refusal is compared.
    #[serde(default)]
    refuses: bool,
    /// Backends whose emitted code is snapshotted for this program, for cases where what the
    /// program prints is not the whole claim. Empty for most cases: running on every backend and
    /// agreeing is the ordinary bar, and a snapshot on top of it is the exception.
    #[serde(default)]
    snapshot: Vec<String>,
    /// The AST shapes this program exercises, in `toylang::tags` terms. Generated by
    /// `tests/tag_corpus.rs` on every run, not hand-authored, so it is read here only to keep
    /// `deny_unknown_fields` from rejecting it -- the fresh value always comes from `toylang::tags`.
    #[serde(default)]
    node_types: Vec<String>,
}

/// What every backend has to do with the program. A case says exactly one of these, because a
/// case that says both, or neither, is one nobody wrote down the point of.
pub enum Expect {
    /// Every backend prints this, and they have to agree.
    Output(String),
    /// Every backend refuses to run it.
    Refusal,
}

pub struct Case {
    pub name: String,
    pub program: String,
    pub input: Option<String>,
    pub expect: Expect,
    pub snapshot: Vec<toylang::Backend>,
}

/// Runs `program` on every backend and reports how the run fell short of `expect`, one line per
/// failure, empty when every backend did what the case asked. The corpus harness and the docs
/// harness both feed programs through this: a docs fragment is a corpus case defined in prose,
/// so what "agrees" means must be one definition, not two.
pub fn agreement_failures(
    name: &str,
    program: &str,
    input: Option<&str>,
    expect: &Expect,
) -> Vec<String> {
    let mut failures = Vec::new();

    if let Expect::Refusal = expect {
        for backend in toylang::Backend::ALL {
            if let Ok(out) = toylang::run_on(program, input, backend) {
                failures.push(format!(
                    "RAN     {name}: {} produced {out:?} instead of refusing",
                    backend.name()
                ));
            }
        }
        return failures;
    }
    let Expect::Output(want) = expect else {
        unreachable!("refusal handled above")
    };

    let mut outputs: Vec<(&str, String)> = Vec::new();
    for backend in toylang::Backend::ALL {
        // A backend that cannot run is reported, never skipped. A report saying every backend
        // agreed when only one of them ran is worse than no report.
        match toylang::run_on(program, input, backend) {
            Ok(out) => outputs.push((backend.name(), out)),
            Err(e) => failures.push(format!(
                "BROKEN  {name}: {} could not run: {e}",
                backend.name()
            )),
        }
    }

    if outputs.len() < toylang::Backend::ALL.len() {
        return failures;
    }

    // Disagreement first, and reported on its own. Which backend matches the expectation is not
    // the point: the language is underspecified either way.
    let (_, first) = &outputs[0];
    if outputs.iter().any(|(_, out)| out != first) {
        let shown: Vec<String> = outputs.iter().map(|(n, o)| format!("{n}={o:?}")).collect();
        failures.push(format!("DISAGREE {name}: {}", shown.join(" ")));
        return failures;
    }

    if first != want {
        failures.push(format!(
            "WRONG   {name}: expected {want:?}, every backend gave {first:?}"
        ));
    }
    failures
}

pub fn dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/corpus")
}

pub fn cases() -> Vec<Case> {
    let dir = dir();
    let mut paths: Vec<PathBuf> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
        .map(|e| e.expect("readable entry").path())
        .filter(|p| p.extension().is_some_and(|e| e == "yaml"))
        .collect();
    paths.sort();

    paths
        .into_iter()
        .map(|path| {
            let name = path
                .file_stem()
                .expect("has a stem")
                .to_string_lossy()
                .into_owned();
            let text = std::fs::read_to_string(&path).expect("readable case");
            let fields: Fields =
                serde_norway::from_str(&text).unwrap_or_else(|e| panic!("{name}: {e}"));
            let snapshot = fields
                .snapshot
                .iter()
                .map(|n| {
                    toylang::Backend::from_name(n)
                        .unwrap_or_else(|| panic!("{name}: `{n}` is not a backend"))
                })
                .collect();
            let expect = match (fields.output, fields.refuses) {
                (Some(output), false) => Expect::Output(output),
                (None, true) => Expect::Refusal,
                (Some(_), true) => panic!("{name}: has both `output` and `refuses`"),
                (None, false) => panic!("{name}: has neither `output` nor `refuses`"),
            };
            Case {
                name,
                program: fields.program,
                input: fields.input,
                expect,
                snapshot,
            }
        })
        .collect()
}
